version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: back.dockerfile
      target: backend_stage 
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      
      # 🗄️ Conexão com o seu MySQL no Amazon RDS
      - SPRING_DATASOURCE_URL=jdbc:mysql://ENDERECO_DO_SEU_RDS_AQUI:3306/NOME_DO_BANCO_DE_DADOS?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=USUARIO_DO_RDS_AQUI
      - SPRING_DATASOURCE_PASSWORD=SENHA_DO_RDS_AQUI
      F
      # ☁️ Credenciais temporárias do S3 (depois mudamos para a Role)
      - AWS_ACCESS_KEY_ID=SUA_ACCESS_KEY_AQUI
      - AWS_SECRET_ACCESS_KEY=SEU_SECRET_KEY_AQUI
      - AWS_REGION=us-east-1
    restart: always

  frontend:
    build:
      context: .
      dockerfile: back.dockerfile
      target: frontend_stage
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend