spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  aws:
    region: us-east-2
    s3:
      bucket-name: lasanhaspec-vehicle-images-dev

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}