spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/lasanhaspec
    username: guilherme
    password: 123456

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  aws:
    region: us-east-2
    s3:
      bucket-name: lasanhaspec-vehicle-images-dev

